[package]
name = "resup"
description = "A frontend for realesrgan-ncnn-vulkan upscaler for terminal."
version = "0.1.0-dev"
edition = "2021"

[dependencies]
clap = "4.3.21"
home = "0.5.5"
serde = { version = "1.0.183", features = ["derive"] }
toml = "0.7.6"
