name: Run Clippy

on: push

jobs:
  clippy:
    runs-on: docker
    container:
      image: node:21-bookworm
    steps:
      - name: Checkout
        uses: https://github.com/actions/checkout@v4
      - name: Setup Rust Toolchain
        uses: https://github.com/actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true
          components: clippy
      - name: Run Clippy
        run: cargo clippy -- -Dwarnings
