name: Build

on: 
  workflow_dispatch:

jobs: 
  build-linux:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        override: true
        components: clippy
    - name: Build Release Binary
      run: cargo build --release
    - name: Upload as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: enjo-linux64
        path: target/release/enjo
  build-win:
    runs-on: windows-latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Rust Toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        override: true
        components: clippy
    - name: Build Release Binary
      run: cargo build --release
    - name: Upload as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: enjo-win64
        path: target\release\enjo.exe

